import type { VenueGraph, VenueId } from '@/lib/types';

const metlife: VenueGraph = {
  venueId: 'metlife',
  venueName: 'MetLife Stadium',
  city: 'East Rutherford, NJ',
  country: 'USA',
  capacity: 82500,
  nodes: [
    { id: 'gate_a',       name: 'Gate A – South Main Entry',     section: 'South Exterior',   level: 0, coords: { x: 50, y: 93 }, accessible: true,  indoor: false },
    { id: 'gate_b',       name: 'Gate B – North Entry',          section: 'North Exterior',   level: 0, coords: { x: 50, y:  7 }, accessible: true,  indoor: false },
    { id: 'gate_c',       name: 'Gate C – East Entry',           section: 'East Exterior',    level: 0, coords: { x: 93, y: 50 }, accessible: true,  indoor: false },
    { id: 'gate_d',       name: 'Gate D – West Entry',           section: 'West Exterior',    level: 0, coords: { x:  7, y: 50 }, accessible: true,  indoor: false },
    { id: 'transit_hub',  name: 'NJ Transit Shuttle Hub',        section: 'South Exterior',   level: 0, coords: { x: 50, y: 98 }, accessible: true,  indoor: false },
    { id: 'lower_south',  name: 'Lower Concourse South',         section: 'Lower Concourse',  level: 1, coords: { x: 50, y: 78 }, accessible: true,  indoor: true  },
    { id: 'lower_north',  name: 'Lower Concourse North',         section: 'Lower Concourse',  level: 1, coords: { x: 50, y: 22 }, accessible: true,  indoor: true  },
    { id: 'lower_east',   name: 'Lower Concourse East',          section: 'Lower Concourse',  level: 1, coords: { x: 78, y: 50 }, accessible: true,  indoor: true  },
    { id: 'lower_west',   name: 'Lower Concourse West',          section: 'Lower Concourse',  level: 1, coords: { x: 22, y: 50 }, accessible: true,  indoor: true  },
    { id: 'food_main',    name: 'Main Food Court',               section: 'Lower Concourse',  level: 1, coords: { x: 50, y: 65 }, accessible: true,  indoor: true  },
    { id: 'upper_east',   name: 'Upper Concourse East',          section: 'Upper Concourse',  level: 2, coords: { x: 83, y: 50 }, accessible: true,  indoor: true  },
    { id: 'upper_west',   name: 'Upper Concourse West',          section: 'Upper Concourse',  level: 2, coords: { x: 17, y: 50 }, accessible: true,  indoor: true  },
    { id: 'field_east',   name: 'Field Level East Tunnel',       section: 'Field Level',      level: 0, coords: { x: 62, y: 50 }, accessible: true,  indoor: true  },
    { id: 'field_west',   name: 'Field Level West Tunnel',       section: 'Field Level',      level: 0, coords: { x: 38, y: 50 }, accessible: true,  indoor: true  },
    { id: 'vip_club',     name: 'MetLife Club – East Wing',      section: 'Club Level',       level: 1, coords: { x: 72, y: 35 }, accessible: true,  indoor: true  },
    { id: 'press_north',  name: 'Media & Press Center',          section: 'North Club',       level: 1, coords: { x: 50, y: 18 }, accessible: true,  indoor: true  },
  ],
  edges: [
    { from: 'transit_hub', to: 'gate_a',      distance: 120, travel: 'walk',      stepFree: true,  capacity: 2000, bidirectional: false },
    { from: 'gate_a',      to: 'lower_south', distance:  80, travel: 'walk',      stepFree: true,  capacity:  800, bidirectional: true  },
    { from: 'gate_b',      to: 'lower_north', distance:  75, travel: 'walk',      stepFree: true,  capacity:  700, bidirectional: true  },
    { from: 'gate_c',      to: 'lower_east',  distance:  85, travel: 'walk',      stepFree: true,  capacity:  750, bidirectional: true  },
    { from: 'gate_d',      to: 'lower_west',  distance:  85, travel: 'walk',      stepFree: true,  capacity:  750, bidirectional: true  },
    { from: 'lower_south', to: 'lower_east',  distance: 155, travel: 'walk',      stepFree: true,  capacity:  600, bidirectional: true  },
    { from: 'lower_east',  to: 'lower_north', distance: 155, travel: 'walk',      stepFree: true,  capacity:  600, bidirectional: true  },
    { from: 'lower_north', to: 'lower_west',  distance: 155, travel: 'walk',      stepFree: true,  capacity:  600, bidirectional: true  },
    { from: 'lower_west',  to: 'lower_south', distance: 155, travel: 'walk',      stepFree: true,  capacity:  600, bidirectional: true  },
    { from: 'lower_south', to: 'food_main',   distance:  40, travel: 'walk',      stepFree: true,  capacity:  500, bidirectional: true  },
    { from: 'lower_east',  to: 'upper_east',  distance:  28, travel: 'escalator', stepFree: false, capacity:  220, bidirectional: false },
    { from: 'lower_east',  to: 'upper_east',  distance:  28, travel: 'elevator',  stepFree: true,  capacity:   15, bidirectional: true  },
    { from: 'lower_west',  to: 'upper_west',  distance:  28, travel: 'escalator', stepFree: false, capacity:  220, bidirectional: false },
    { from: 'lower_west',  to: 'upper_west',  distance:  28, travel: 'elevator',  stepFree: true,  capacity:   15, bidirectional: true  },
    { from: 'upper_east',  to: 'upper_west',  distance: 195, travel: 'walk',      stepFree: true,  capacity:  400, bidirectional: true  },
    { from: 'lower_south', to: 'field_east',  distance:  55, travel: 'ramp',      stepFree: true,  capacity:  300, bidirectional: true  },
    { from: 'lower_south', to: 'field_west',  distance:  55, travel: 'ramp',      stepFree: true,  capacity:  300, bidirectional: true  },
    { from: 'field_east',  to: 'field_west',  distance:  50, travel: 'walk',      stepFree: true,  capacity:  200, bidirectional: true  },
    { from: 'lower_east',  to: 'vip_club',    distance:  55, travel: 'walk',      stepFree: true,  capacity:  200, bidirectional: true  },
    { from: 'lower_north', to: 'press_north', distance:  30, travel: 'walk',      stepFree: true,  capacity:  150, bidirectional: true  },
  ],
  facilities: [
    { id: 'ml_trn_a', type: 'turnstile',          nodeId: 'gate_a',      name: 'Gate A Turnstiles',        description: 'Main entry turnstiles, 24 lanes',             accessible: true,  capacity: 1200, operatingHours: '3h before kickoff to 1h after' },
    { id: 'ml_trn_b', type: 'turnstile',          nodeId: 'gate_b',      name: 'Gate B Turnstiles',        description: 'North entry, 18 lanes',                       accessible: true,  capacity: 900,  operatingHours: '3h before kickoff to 1h after' },
    { id: 'ml_trn_c', type: 'turnstile',          nodeId: 'gate_c',      name: 'Gate C Turnstiles',        description: 'East entry, 20 lanes',                        accessible: true,  capacity: 1000, operatingHours: '3h before kickoff to 1h after' },
    { id: 'ml_trn_d', type: 'turnstile',          nodeId: 'gate_d',      name: 'Gate D Turnstiles',        description: 'West entry, 20 lanes',                        accessible: true,  capacity: 1000, operatingHours: '3h before kickoff to 1h after' },
    { id: 'ml_rst_s', type: 'restroom',           nodeId: 'lower_south', name: 'Restrooms – South Lower',  description: '12 stalls each side',                         accessible: false, capacity: 120,  operatingHours: 'During event' },
    { id: 'ml_rst_n', type: 'restroom',           nodeId: 'lower_north', name: 'Restrooms – North Lower',  description: '10 stalls each side',                         accessible: false, capacity: 100,  operatingHours: 'During event' },
    { id: 'ml_rst_u', type: 'restroom',           nodeId: 'upper_east',  name: 'Restrooms – Upper East',   description: '8 stalls each side',                          accessible: false, capacity:  80,  operatingHours: 'During event' },
    { id: 'ml_arc',   type: 'accessible_restroom', nodeId: 'lower_west', name: 'ADA Restroom – West',      description: 'Fully accessible, companion care available',  accessible: true,  capacity:   4,  operatingHours: 'During event' },
    { id: 'ml_fca',   type: 'food_court',         nodeId: 'food_main',   name: 'Champions Food Hall',      description: 'Full-service food hall, 30 vendors',          accessible: true,  capacity: 800,  operatingHours: '2.5h before kickoff to end of match' },
    { id: 'ml_fcb',   type: 'food_court',         nodeId: 'lower_east',  name: 'East Concession Stand',    description: 'Quick-serve concessions',                     accessible: true,  capacity: 300,  operatingHours: '2h before kickoff to end of match' },
    { id: 'ml_fa1',   type: 'first_aid',          nodeId: 'lower_east',  name: 'First Aid – Lower East',   description: 'EMT staffed, AED on site',                    accessible: true,  capacity:  10,  operatingHours: 'During event' },
    { id: 'ml_fa2',   type: 'first_aid',          nodeId: 'field_east',  name: 'First Aid – Field Level',  description: 'Full medical response team',                  accessible: true,  capacity:  20,  operatingHours: 'During event' },
    { id: 'ml_atm',   type: 'atm',                nodeId: 'lower_east',  name: 'ATM Bank – East',          description: '6 ATM machines',                              accessible: true },
    { id: 'ml_wat_s', type: 'water_station',      nodeId: 'lower_south', name: 'Water Station South',      description: 'Free filtered water refill point',            accessible: true },
    { id: 'ml_wat_u', type: 'water_station',      nodeId: 'upper_east',  name: 'Water Station Upper',      description: 'Free filtered water refill point',            accessible: true },
    { id: 'ml_chg',   type: 'charging_station',   nodeId: 'vip_club',    name: 'Device Charging Hub',      description: '40-port USB & wireless charging',             accessible: true },
    { id: 'ml_merch', type: 'merchandise',        nodeId: 'lower_south', name: 'Official FIFA Store',      description: 'Official WC 2026 merchandise',                accessible: true,  capacity: 200,  operatingHours: '3h before kickoff to 1h after' },
    { id: 'ml_sens',  type: 'sensory_room',       nodeId: 'lower_west',  name: 'Sensory Inclusion Room',   description: 'Quiet space with low-stimulation environment', accessible: true,  capacity:  15,  operatingHours: 'During event' },
    { id: 'ml_vip',   type: 'vip_lounge',         nodeId: 'vip_club',    name: 'MetLife Club Lounge',      description: 'Premium hospitality, sit-down dining',        accessible: true,  capacity: 400,  operatingHours: '3h before kickoff to 2h after' },
    { id: 'ml_prs',   type: 'press_area',         nodeId: 'press_north', name: 'FIFA Media Centre',        description: 'Credentialed press only, broadcast desks',    accessible: true,  capacity: 300,  operatingHours: '4h before kickoff to 3h after' },
    { id: 'ml_trn',   type: 'transit_hub',        nodeId: 'transit_hub', name: 'NJ Transit Shuttle Stop',  description: 'Buses to Penn Station & Secaucus Junction',   accessible: true },
  ],
};

const sofi: VenueGraph = {
  venueId: 'sofi',
  venueName: 'SoFi Stadium',
  city: 'Inglewood, CA',
  country: 'USA',
  capacity: 70240,
  nodes: [
    { id: 'gate_1',       name: 'Gate 1 – South Main Entry',    section: 'South Exterior',    level: 0, coords: { x: 50, y: 93 }, accessible: true,  indoor: false },
    { id: 'gate_2',       name: 'Gate 2 – North Entry',         section: 'North Exterior',    level: 0, coords: { x: 50, y:  7 }, accessible: true,  indoor: false },
    { id: 'gate_3',       name: 'Gate 3 – East Entry',          section: 'East Exterior',     level: 0, coords: { x: 93, y: 50 }, accessible: true,  indoor: false },
    { id: 'gate_4',       name: 'Gate 4 – West Entry',          section: 'West Exterior',     level: 0, coords: { x:  7, y: 50 }, accessible: true,  indoor: false },
    { id: 'main_concourse', name: 'Main Concourse Ring',        section: 'Main Concourse',    level: 1, coords: { x: 50, y: 50 }, accessible: true,  indoor: true  },
    { id: 'conc_south',   name: 'Concourse South Hub',          section: 'Main Concourse',    level: 1, coords: { x: 50, y: 75 }, accessible: true,  indoor: true  },
    { id: 'conc_north',   name: 'Concourse North Hub',          section: 'Main Concourse',    level: 1, coords: { x: 50, y: 25 }, accessible: true,  indoor: true  },
    { id: 'conc_east',    name: 'Concourse East Hub',           section: 'Main Concourse',    level: 1, coords: { x: 75, y: 50 }, accessible: true,  indoor: true  },
    { id: 'conc_west',    name: 'Concourse West Hub',           section: 'Main Concourse',    level: 1, coords: { x: 25, y: 50 }, accessible: true,  indoor: true  },
    { id: 'upper_north',  name: 'Peristyle – Upper North',      section: 'Upper Bowl',        level: 2, coords: { x: 50, y: 18 }, accessible: true,  indoor: true  },
    { id: 'upper_south',  name: 'Peristyle – Upper South',      section: 'Upper Bowl',        level: 2, coords: { x: 50, y: 82 }, accessible: true,  indoor: true  },
    { id: 'field_tunnel', name: 'Field Tunnel Access',          section: 'Field Level',       level: 0, coords: { x: 50, y: 55 }, accessible: true,  indoor: true  },
    { id: 'im_plex',      name: 'InfinityScreen Plaza',         section: 'Main Concourse',    level: 1, coords: { x: 50, y: 62 }, accessible: true,  indoor: true  },
    { id: 'club_level',   name: 'DraftKings Club Level',        section: 'Club Level',        level: 1, coords: { x: 65, y: 40 }, accessible: true,  indoor: true  },
    { id: 'metro_plaza',  name: 'Metro Rail Plaza',             section: 'South Exterior',    level: 0, coords: { x: 35, y: 97 }, accessible: true,  indoor: false },
    { id: 'sky_lounge',   name: 'SoFi Sky Lounge',              section: 'Premium',           level: 2, coords: { x: 70, y: 30 }, accessible: true,  indoor: true  },
  ],
  edges: [
    { from: 'metro_plaza',  to: 'gate_1',       distance:  90, travel: 'walk',      stepFree: true,  capacity: 3000, bidirectional: false },
    { from: 'gate_1',       to: 'conc_south',   distance:  70, travel: 'walk',      stepFree: true,  capacity:  900, bidirectional: true  },
    { from: 'gate_2',       to: 'conc_north',   distance:  70, travel: 'walk',      stepFree: true,  capacity:  800, bidirectional: true  },
    { from: 'gate_3',       to: 'conc_east',    distance:  75, travel: 'walk',      stepFree: true,  capacity:  850, bidirectional: true  },
    { from: 'gate_4',       to: 'conc_west',    distance:  75, travel: 'walk',      stepFree: true,  capacity:  850, bidirectional: true  },
    { from: 'conc_south',   to: 'conc_east',    distance: 140, travel: 'walk',      stepFree: true,  capacity:  600, bidirectional: true  },
    { from: 'conc_east',    to: 'conc_north',   distance: 140, travel: 'walk',      stepFree: true,  capacity:  600, bidirectional: true  },
    { from: 'conc_north',   to: 'conc_west',    distance: 140, travel: 'walk',      stepFree: true,  capacity:  600, bidirectional: true  },
    { from: 'conc_west',    to: 'conc_south',   distance: 140, travel: 'walk',      stepFree: true,  capacity:  600, bidirectional: true  },
    { from: 'conc_south',   to: 'im_plex',      distance:  35, travel: 'walk',      stepFree: true,  capacity:  700, bidirectional: true  },
    { from: 'im_plex',      to: 'field_tunnel', distance:  30, travel: 'ramp',      stepFree: true,  capacity:  250, bidirectional: true  },
    { from: 'conc_north',   to: 'upper_north',  distance:  26, travel: 'escalator', stepFree: false, capacity:  200, bidirectional: false },
    { from: 'conc_north',   to: 'upper_north',  distance:  26, travel: 'elevator',  stepFree: true,  capacity:   12, bidirectional: true  },
    { from: 'conc_south',   to: 'upper_south',  distance:  26, travel: 'escalator', stepFree: false, capacity:  200, bidirectional: false },
    { from: 'conc_south',   to: 'upper_south',  distance:  26, travel: 'elevator',  stepFree: true,  capacity:   12, bidirectional: true  },
    { from: 'upper_north',  to: 'upper_south',  distance: 180, travel: 'walk',      stepFree: true,  capacity:  350, bidirectional: true  },
    { from: 'conc_east',    to: 'club_level',   distance:  50, travel: 'walk',      stepFree: true,  capacity:  200, bidirectional: true  },
    { from: 'club_level',   to: 'sky_lounge',   distance:  30, travel: 'stairs',    stepFree: false, capacity:  100, bidirectional: true  },
    { from: 'club_level',   to: 'sky_lounge',   distance:  30, travel: 'elevator',  stepFree: true,  capacity:   10, bidirectional: true  },
    { from: 'main_concourse', to: 'conc_south', distance:  55, travel: 'walk',      stepFree: true,  capacity:  500, bidirectional: true  },
  ],
  facilities: [
    { id: 'sf_trn_1', type: 'turnstile',          nodeId: 'gate_1',       name: 'Gate 1 Turnstiles',          description: '22 lanes, facial recognition option',         accessible: true,  capacity: 1100 },
    { id: 'sf_trn_2', type: 'turnstile',          nodeId: 'gate_2',       name: 'Gate 2 Turnstiles',          description: '18 lanes',                                    accessible: true,  capacity:  900 },
    { id: 'sf_trn_3', type: 'turnstile',          nodeId: 'gate_3',       name: 'Gate 3 Turnstiles',          description: '20 lanes',                                    accessible: true,  capacity: 1000 },
    { id: 'sf_trn_4', type: 'turnstile',          nodeId: 'gate_4',       name: 'Gate 4 Turnstiles',          description: '20 lanes',                                    accessible: true,  capacity: 1000 },
    { id: 'sf_rst_s', type: 'restroom',           nodeId: 'conc_south',   name: 'Restrooms – South',          description: '14 stalls per side',                          accessible: false, capacity: 140  },
    { id: 'sf_rst_n', type: 'restroom',           nodeId: 'conc_north',   name: 'Restrooms – North',          description: '12 stalls per side',                          accessible: false, capacity: 120  },
    { id: 'sf_arc',   type: 'accessible_restroom', nodeId: 'conc_west',   name: 'ADA Restroom – West',        description: 'Fully accessible, changing table',            accessible: true,  capacity:   4  },
    { id: 'sf_fca',   type: 'food_court',         nodeId: 'im_plex',      name: 'InfinityScreen Food Court',  description: 'Gourmet LA street food, 40 vendors',          accessible: true,  capacity: 600  },
    { id: 'sf_fcb',   type: 'food_court',         nodeId: 'conc_east',    name: 'East Concessions',           description: 'Quick-serve, mobile order pickup',            accessible: true,  capacity: 350  },
    { id: 'sf_fa1',   type: 'first_aid',          nodeId: 'conc_south',   name: 'First Aid – South',          description: 'EMT & paramedic staffed',                     accessible: true,  capacity:  12  },
    { id: 'sf_fa2',   type: 'first_aid',          nodeId: 'field_tunnel', name: 'First Aid – Field',          description: 'Full trauma response, defibrillator',         accessible: true,  capacity:  20  },
    { id: 'sf_atm',   type: 'atm',                nodeId: 'conc_east',    name: 'ATM Cluster – East',         description: '8 machines, multiple banks',                  accessible: true                 },
    { id: 'sf_wat',   type: 'water_station',      nodeId: 'conc_south',   name: 'Hydration Station',          description: 'Eco refill, 8 taps',                          accessible: true                 },
    { id: 'sf_chg',   type: 'charging_station',   nodeId: 'club_level',   name: 'Charging Lounge',            description: '50 USB-C & wireless pads',                    accessible: true                 },
    { id: 'sf_merch', type: 'merchandise',        nodeId: 'conc_south',   name: 'FIFA WC Store – SoFi',       description: 'Official merchandise, 2,000 sq ft',           accessible: true,  capacity: 250  },
    { id: 'sf_sens',  type: 'sensory_room',       nodeId: 'conc_west',    name: 'Sensory Room',               description: 'KultureCity certified, low-stimulation',      accessible: true,  capacity:  20  },
    { id: 'sf_fam',   type: 'family_room',        nodeId: 'conc_north',   name: 'Family Room',                description: 'Nursing room & family lounge',                accessible: true,  capacity:  25  },
    { id: 'sf_vip',   type: 'vip_lounge',         nodeId: 'sky_lounge',   name: 'SoFi Sky Lounge',            description: 'Rooftop premium lounge, 360° views',          accessible: true,  capacity: 300  },
    { id: 'sf_mtr',   type: 'transit_hub',        nodeId: 'metro_plaza',  name: 'Metro K Line – Inglewood',  description: 'Direct rail to downtown LA & LAX',            accessible: true                 },
    { id: 'sf_prs',   type: 'press_area',         nodeId: 'conc_north',   name: 'FIFA Media Centre – SoFi',   description: 'Broadcast booths, mixed zone, tribune',       accessible: true,  capacity: 280  },
  ],
};

const attdallas: VenueGraph = {
  venueId: 'attdallas',
  venueName: 'AT&T Stadium',
  city: 'Arlington, TX',
  country: 'USA',
  capacity: 80000,
  nodes: [
    { id: 'gate_a',      name: 'Gate A – East Main Entry',   section: 'East Exterior',   level: 0, coords: { x: 93, y: 50 }, accessible: true,  indoor: false },
    { id: 'gate_b',      name: 'Gate B – West Entry',        section: 'West Exterior',   level: 0, coords: { x:  7, y: 50 }, accessible: true,  indoor: false },
    { id: 'gate_c',      name: 'Gate C – North Entry',       section: 'North Exterior',  level: 0, coords: { x: 50, y:  7 }, accessible: true,  indoor: false },
    { id: 'gate_d',      name: 'Gate D – South Entry',       section: 'South Exterior',  level: 0, coords: { x: 50, y: 93 }, accessible: true,  indoor: false },
    { id: 'main_plaza',  name: 'Main East Plaza',            section: 'East Plaza',      level: 0, coords: { x: 85, y: 50 }, accessible: true,  indoor: false },
    { id: 'conc_east',   name: 'East Concourse',             section: 'Main Concourse',  level: 1, coords: { x: 75, y: 50 }, accessible: true,  indoor: true  },
    { id: 'conc_west',   name: 'West Concourse',             section: 'Main Concourse',  level: 1, coords: { x: 25, y: 50 }, accessible: true,  indoor: true  },
    { id: 'conc_north',  name: 'North Concourse',            section: 'Main Concourse',  level: 1, coords: { x: 50, y: 22 }, accessible: true,  indoor: true  },
    { id: 'conc_south',  name: 'South Concourse',            section: 'Main Concourse',  level: 1, coords: { x: 50, y: 78 }, accessible: true,  indoor: true  },
    { id: 'upper_e',     name: 'Upper Level East',           section: 'Upper Bowl',      level: 2, coords: { x: 80, y: 50 }, accessible: true,  indoor: true  },
    { id: 'upper_w',     name: 'Upper Level West',           section: 'Upper Bowl',      level: 2, coords: { x: 20, y: 50 }, accessible: true,  indoor: true  },
    { id: 'field_a',     name: 'Field Access East',          section: 'Field Level',     level: 0, coords: { x: 63, y: 50 }, accessible: true,  indoor: true  },
    { id: 'club_east',   name: 'Bud Light Club East',        section: 'Club Level',      level: 1, coords: { x: 70, y: 38 }, accessible: true,  indoor: true  },
    { id: 'atrium',      name: 'Grand Atrium',               section: 'East Lobby',      level: 1, coords: { x: 80, y: 62 }, accessible: true,  indoor: true  },
    { id: 'transit_lot', name: 'Trinity Railway Express Hub',section: 'Exterior Lot',    level: 0, coords: { x: 50, y: 98 }, accessible: true,  indoor: false },
  ],
  edges: [
    { from: 'transit_lot', to: 'gate_d',     distance: 200, travel: 'walk',      stepFree: true,  capacity: 2500, bidirectional: false },
    { from: 'gate_a',      to: 'main_plaza', distance:  40, travel: 'walk',      stepFree: true,  capacity: 1000, bidirectional: true  },
    { from: 'main_plaza',  to: 'conc_east',  distance:  60, travel: 'walk',      stepFree: true,  capacity:  900, bidirectional: true  },
    { from: 'gate_b',      to: 'conc_west',  distance:  80, travel: 'walk',      stepFree: true,  capacity:  800, bidirectional: true  },
    { from: 'gate_c',      to: 'conc_north', distance:  75, travel: 'walk',      stepFree: true,  capacity:  750, bidirectional: true  },
    { from: 'gate_d',      to: 'conc_south', distance:  75, travel: 'walk',      stepFree: true,  capacity:  750, bidirectional: true  },
    { from: 'conc_east',   to: 'conc_north', distance: 150, travel: 'walk',      stepFree: true,  capacity:  600, bidirectional: true  },
    { from: 'conc_north',  to: 'conc_west',  distance: 150, travel: 'walk',      stepFree: true,  capacity:  600, bidirectional: true  },
    { from: 'conc_west',   to: 'conc_south', distance: 150, travel: 'walk',      stepFree: true,  capacity:  600, bidirectional: true  },
    { from: 'conc_south',  to: 'conc_east',  distance: 150, travel: 'walk',      stepFree: true,  capacity:  600, bidirectional: true  },
    { from: 'conc_east',   to: 'upper_e',    distance:  30, travel: 'escalator', stepFree: false, capacity:  220, bidirectional: false },
    { from: 'conc_east',   to: 'upper_e',    distance:  30, travel: 'elevator',  stepFree: true,  capacity:   15, bidirectional: true  },
    { from: 'conc_west',   to: 'upper_w',    distance:  30, travel: 'escalator', stepFree: false, capacity:  220, bidirectional: false },
    { from: 'conc_west',   to: 'upper_w',    distance:  30, travel: 'elevator',  stepFree: true,  capacity:   15, bidirectional: true  },
    { from: 'upper_e',     to: 'upper_w',    distance: 200, travel: 'walk',      stepFree: true,  capacity:  400, bidirectional: true  },
    { from: 'conc_east',   to: 'field_a',    distance:  50, travel: 'ramp',      stepFree: true,  capacity:  300, bidirectional: true  },
    { from: 'conc_east',   to: 'atrium',     distance:  40, travel: 'walk',      stepFree: true,  capacity:  500, bidirectional: true  },
    { from: 'conc_east',   to: 'club_east',  distance:  45, travel: 'walk',      stepFree: true,  capacity:  200, bidirectional: true  },
  ],
  facilities: [
    { id: 'at_trn_a', type: 'turnstile',          nodeId: 'gate_a',      name: 'Gate A Turnstiles',       description: '24 lanes, biometric entry',                   accessible: true,  capacity: 1200 },
    { id: 'at_trn_b', type: 'turnstile',          nodeId: 'gate_b',      name: 'Gate B Turnstiles',       description: '20 lanes',                                    accessible: true,  capacity: 1000 },
    { id: 'at_trn_c', type: 'turnstile',          nodeId: 'gate_c',      name: 'Gate C Turnstiles',       description: '18 lanes',                                    accessible: true,  capacity:  900 },
    { id: 'at_trn_d', type: 'turnstile',          nodeId: 'gate_d',      name: 'Gate D Turnstiles',       description: '18 lanes',                                    accessible: true,  capacity:  900 },
    { id: 'at_rst_e', type: 'restroom',           nodeId: 'conc_east',   name: 'Restrooms – East',        description: '16 stalls per side',                          accessible: false, capacity: 160  },
    { id: 'at_rst_w', type: 'restroom',           nodeId: 'conc_west',   name: 'Restrooms – West',        description: '14 stalls per side',                          accessible: false, capacity: 140  },
    { id: 'at_arc',   type: 'accessible_restroom', nodeId: 'conc_south', name: 'ADA Restroom – South',    description: 'Accessible, changing table, companion care',  accessible: true,  capacity:   5  },
    { id: 'at_fca',   type: 'food_court',         nodeId: 'atrium',      name: 'Grand Atrium Food Court', description: '35 vendors, Texas BBQ & international',       accessible: true,  capacity: 700  },
    { id: 'at_fcb',   type: 'food_court',         nodeId: 'conc_north',  name: 'North Concessions',       description: 'Grab-and-go, mobile checkout',                accessible: true,  capacity: 350  },
    { id: 'at_fa1',   type: 'first_aid',          nodeId: 'conc_east',   name: 'First Aid – East',        description: 'EMT staffed, AED available',                  accessible: true,  capacity:  12  },
    { id: 'at_fa2',   type: 'first_aid',          nodeId: 'field_a',     name: 'First Aid – Field',       description: 'Trauma response unit',                        accessible: true,  capacity:  20  },
    { id: 'at_atm',   type: 'atm',                nodeId: 'atrium',      name: 'ATM Bank – Atrium',       description: '10 machines',                                 accessible: true                 },
    { id: 'at_wat_e', type: 'water_station',      nodeId: 'conc_east',   name: 'Water Station East',      description: 'Chilled filtered water, 10 taps',             accessible: true                 },
    { id: 'at_wat_u', type: 'water_station',      nodeId: 'upper_e',     name: 'Water Station Upper',     description: 'Filtered water, 6 taps',                      accessible: true                 },
    { id: 'at_chg',   type: 'charging_station',   nodeId: 'club_east',   name: 'Charging Hub – Club',     description: '60 USB & wireless charging pads',             accessible: true                 },
    { id: 'at_merch', type: 'merchandise',        nodeId: 'conc_east',   name: 'Official FIFA Store',     description: 'WC 2026 & Cowboys gear',                      accessible: true,  capacity: 300  },
    { id: 'at_sens',  type: 'sensory_room',       nodeId: 'conc_west',   name: 'Quiet Room West',         description: 'Low-stimulation space, earplugs provided',    accessible: true,  capacity:  15  },
    { id: 'at_vip',   type: 'vip_lounge',         nodeId: 'club_east',   name: 'Bud Light Club',          description: 'Club-level dining and bar',                   accessible: true,  capacity: 500  },
    { id: 'at_trn',   type: 'transit_hub',        nodeId: 'transit_lot', name: 'TRE Rail Connection',     description: 'Trinity Railway Express to Fort Worth/Dallas', accessible: true                 },
    { id: 'at_prs',   type: 'press_area',         nodeId: 'conc_north',  name: 'Press Tribune',           description: 'FIFA-accredited media zone',                  accessible: true,  capacity: 250  },
  ],
};

const levis: VenueGraph = {
  venueId: 'levis',
  venueName: "Levi's Stadium",
  city: 'Santa Clara, CA',
  country: 'USA',
  capacity: 68500,
  nodes: [
    { id: 'gate_a',      name: "Gate A – South Entry",         section: 'South Exterior',   level: 0, coords: { x: 50, y: 92 }, accessible: true,  indoor: false },
    { id: 'gate_b',      name: 'Gate B – North Entry',         section: 'North Exterior',   level: 0, coords: { x: 50, y:  8 }, accessible: true,  indoor: false },
    { id: 'gate_c',      name: 'Gate C – East Entry',          section: 'East Exterior',    level: 0, coords: { x: 92, y: 50 }, accessible: true,  indoor: false },
    { id: 'gate_d',      name: 'Gate D – West Entry',          section: 'West Exterior',    level: 0, coords: { x:  8, y: 50 }, accessible: true,  indoor: false },
    { id: 'main_plaza',  name: 'South Fan Plaza',              section: 'South Plaza',      level: 0, coords: { x: 50, y: 85 }, accessible: true,  indoor: false },
    { id: 'conc_lower',  name: 'Lower Concourse Ring',         section: 'Lower Concourse',  level: 1, coords: { x: 50, y: 50 }, accessible: true,  indoor: true  },
    { id: 'conc_se',     name: 'Lower Concourse SE',           section: 'Lower Concourse',  level: 1, coords: { x: 72, y: 72 }, accessible: true,  indoor: true  },
    { id: 'conc_ne',     name: 'Lower Concourse NE',           section: 'Lower Concourse',  level: 1, coords: { x: 72, y: 28 }, accessible: true,  indoor: true  },
    { id: 'conc_sw',     name: 'Lower Concourse SW',           section: 'Lower Concourse',  level: 1, coords: { x: 28, y: 72 }, accessible: true,  indoor: true  },
    { id: 'conc_nw',     name: 'Lower Concourse NW',           section: 'Lower Concourse',  level: 1, coords: { x: 28, y: 28 }, accessible: true,  indoor: true  },
    { id: 'upper_se',    name: 'Upper Bowl SE',                section: 'Upper Bowl',       level: 2, coords: { x: 78, y: 75 }, accessible: true,  indoor: true  },
    { id: 'upper_sw',    name: 'Upper Bowl SW',                section: 'Upper Bowl',       level: 2, coords: { x: 22, y: 75 }, accessible: true,  indoor: true  },
    { id: 'field_north', name: 'Field Tunnel North',           section: 'Field Level',      level: 0, coords: { x: 50, y: 42 }, accessible: true,  indoor: true  },
    { id: 'levi_lounge', name: "Levi's 501 Club",              section: 'Club Level',       level: 1, coords: { x: 68, y: 42 }, accessible: true,  indoor: true  },
    { id: 'vta_plaza',   name: 'VTA Light Rail Plaza',         section: 'Exterior',         level: 0, coords: { x: 12, y: 92 }, accessible: true,  indoor: false },
  ],
  edges: [
    { from: 'vta_plaza',  to: 'gate_d',      distance: 180, travel: 'walk',      stepFree: true,  capacity: 2000, bidirectional: false },
    { from: 'gate_a',     to: 'main_plaza',  distance:  50, travel: 'walk',      stepFree: true,  capacity: 1000, bidirectional: true  },
    { from: 'main_plaza', to: 'conc_se',     distance:  70, travel: 'walk',      stepFree: true,  capacity:  800, bidirectional: true  },
    { from: 'main_plaza', to: 'conc_sw',     distance:  70, travel: 'walk',      stepFree: true,  capacity:  800, bidirectional: true  },
    { from: 'gate_b',     to: 'conc_ne',     distance:  80, travel: 'walk',      stepFree: true,  capacity:  700, bidirectional: true  },
    { from: 'gate_b',     to: 'conc_nw',     distance:  80, travel: 'walk',      stepFree: true,  capacity:  700, bidirectional: true  },
    { from: 'gate_c',     to: 'conc_se',     distance:  75, travel: 'walk',      stepFree: true,  capacity:  750, bidirectional: true  },
    { from: 'gate_d',     to: 'conc_sw',     distance:  75, travel: 'walk',      stepFree: true,  capacity:  750, bidirectional: true  },
    { from: 'conc_se',    to: 'conc_ne',     distance: 130, travel: 'walk',      stepFree: true,  capacity:  600, bidirectional: true  },
    { from: 'conc_ne',    to: 'conc_nw',     distance: 130, travel: 'walk',      stepFree: true,  capacity:  600, bidirectional: true  },
    { from: 'conc_nw',    to: 'conc_sw',     distance: 130, travel: 'walk',      stepFree: true,  capacity:  600, bidirectional: true  },
    { from: 'conc_se',    to: 'upper_se',    distance:  25, travel: 'escalator', stepFree: false, capacity:  200, bidirectional: false },
    { from: 'conc_se',    to: 'upper_se',    distance:  25, travel: 'elevator',  stepFree: true,  capacity:   12, bidirectional: true  },
    { from: 'conc_sw',    to: 'upper_sw',    distance:  25, travel: 'escalator', stepFree: false, capacity:  200, bidirectional: false },
    { from: 'conc_sw',    to: 'upper_sw',    distance:  25, travel: 'elevator',  stepFree: true,  capacity:   12, bidirectional: true  },
    { from: 'conc_lower', to: 'field_north', distance:  50, travel: 'ramp',      stepFree: true,  capacity:  250, bidirectional: true  },
    { from: 'conc_se',    to: 'levi_lounge', distance:  45, travel: 'walk',      stepFree: true,  capacity:  180, bidirectional: true  },
  ],
  facilities: [
    { id: 'lv_trn_a', type: 'turnstile',          nodeId: 'gate_a',      name: 'Gate A Turnstiles',      description: '20 lanes',                                    accessible: true,  capacity: 1000 },
    { id: 'lv_trn_b', type: 'turnstile',          nodeId: 'gate_b',      name: 'Gate B Turnstiles',      description: '16 lanes',                                    accessible: true,  capacity:  800 },
    { id: 'lv_trn_c', type: 'turnstile',          nodeId: 'gate_c',      name: 'Gate C Turnstiles',      description: '18 lanes',                                    accessible: true,  capacity:  900 },
    { id: 'lv_trn_d', type: 'turnstile',          nodeId: 'gate_d',      name: 'Gate D Turnstiles',      description: '18 lanes',                                    accessible: true,  capacity:  900 },
    { id: 'lv_rst_s', type: 'restroom',           nodeId: 'conc_se',     name: 'Restrooms – SE',         description: '12 stalls per side',                          accessible: false, capacity: 120  },
    { id: 'lv_rst_n', type: 'restroom',           nodeId: 'conc_nw',     name: 'Restrooms – NW',         description: '10 stalls per side',                          accessible: false, capacity: 100  },
    { id: 'lv_arc',   type: 'accessible_restroom', nodeId: 'conc_sw',    name: 'ADA Restroom – SW',      description: 'Fully accessible with companion care',        accessible: true,  capacity:   4  },
    { id: 'lv_fca',   type: 'food_court',         nodeId: 'main_plaza',  name: 'South Fan Plaza Eats',   description: 'Outdoor food village, 20 vendors',            accessible: true,  capacity: 500  },
    { id: 'lv_fcb',   type: 'food_court',         nodeId: 'conc_ne',     name: 'NE Concessions',         description: 'Silicon Valley fusion & classics',            accessible: true,  capacity: 300  },
    { id: 'lv_fa1',   type: 'first_aid',          nodeId: 'conc_se',     name: 'First Aid – SE',         description: 'EMT staffed, oxygen on site',                 accessible: true,  capacity:  12  },
    { id: 'lv_fa2',   type: 'first_aid',          nodeId: 'field_north', name: 'First Aid – Field',      description: 'Trauma bay, physician on duty',               accessible: true,  capacity:  20  },
    { id: 'lv_atm',   type: 'atm',                nodeId: 'conc_se',     name: 'ATM Bank – SE',          description: '6 machines',                                  accessible: true                 },
    { id: 'lv_wat',   type: 'water_station',      nodeId: 'conc_sw',     name: 'Hydration Station',      description: '8 chilled taps',                              accessible: true                 },
    { id: 'lv_chg',   type: 'charging_station',   nodeId: 'levi_lounge', name: 'Tech Charging Hub',      description: '60 USB & MagSafe pads',                       accessible: true                 },
    { id: 'lv_merch', type: 'merchandise',        nodeId: 'main_plaza',  name: "FIFA WC Store – Levi's", description: 'Official WC 2026 merchandise',                accessible: true,  capacity: 250  },
    { id: 'lv_sens',  type: 'sensory_room',       nodeId: 'conc_nw',     name: 'Quiet Room NW',          description: 'Low-stimulation environment',                 accessible: true,  capacity:  15  },
    { id: 'lv_vip',   type: 'vip_lounge',         nodeId: 'levi_lounge', name: "Levi's 501 Club",        description: 'Premium all-inclusive club experience',       accessible: true,  capacity: 350  },
    { id: 'lv_trn',   type: 'transit_hub',        nodeId: 'vta_plaza',   name: 'VTA Light Rail',         description: 'Direct service to San Jose Diridon',          accessible: true                 },
    { id: 'lv_prs',   type: 'press_area',         nodeId: 'conc_ne',     name: 'Media Centre – NE',      description: 'FIFA press tribune, mixed zone',              accessible: true,  capacity: 220  },
  ],
};

const hardrock: VenueGraph = {
  venueId: 'hardrock',
  venueName: 'Hard Rock Stadium',
  city: 'Miami Gardens, FL',
  country: 'USA',
  capacity: 65326,
  nodes: [
    { id: 'gate_1',     name: 'Gate 1 – South Entry',          section: 'South Exterior',  level: 0, coords: { x: 50, y: 93 }, accessible: true,  indoor: false },
    { id: 'gate_2',     name: 'Gate 2 – North Entry',          section: 'North Exterior',  level: 0, coords: { x: 50, y:  7 }, accessible: true,  indoor: false },
    { id: 'gate_3',     name: 'Gate 3 – East Entry',           section: 'East Exterior',   level: 0, coords: { x: 92, y: 50 }, accessible: true,  indoor: false },
    { id: 'gate_4',     name: 'Gate 4 – West Entry',           section: 'West Exterior',   level: 0, coords: { x:  8, y: 50 }, accessible: true,  indoor: false },
    { id: 'shade_deck', name: 'Shade Canopy Concourse',        section: 'Main Concourse',  level: 1, coords: { x: 50, y: 50 }, accessible: true,  indoor: false },
    { id: 'conc_south', name: 'Lower Concourse South',         section: 'Lower Concourse', level: 1, coords: { x: 50, y: 75 }, accessible: true,  indoor: false },
    { id: 'conc_north', name: 'Lower Concourse North',         section: 'Lower Concourse', level: 1, coords: { x: 50, y: 25 }, accessible: true,  indoor: false },
    { id: 'conc_east',  name: 'Lower Concourse East',          section: 'Lower Concourse', level: 1, coords: { x: 75, y: 50 }, accessible: true,  indoor: false },
    { id: 'conc_west',  name: 'Lower Concourse West',          section: 'Lower Concourse', level: 1, coords: { x: 25, y: 50 }, accessible: true,  indoor: false },
    { id: 'upper_e',    name: 'Upper Deck East',               section: 'Upper Bowl',      level: 2, coords: { x: 80, y: 50 }, accessible: true,  indoor: false },
    { id: 'upper_w',    name: 'Upper Deck West',               section: 'Upper Bowl',      level: 2, coords: { x: 20, y: 50 }, accessible: true,  indoor: false },
    { id: 'field_s',    name: 'Field Access South',            section: 'Field Level',     level: 0, coords: { x: 50, y: 62 }, accessible: true,  indoor: false },
    { id: 'club_1',     name: 'Hard Rock Social Club',         section: 'Club Level',      level: 1, coords: { x: 65, y: 38 }, accessible: true,  indoor: true  },
    { id: 'mia_grdn',   name: 'Miami Gardens Fan Zone',        section: 'Exterior',        level: 0, coords: { x: 50, y: 98 }, accessible: true,  indoor: false },
    { id: 'parking_hub',name: 'Smart Parking Hub',             section: 'Exterior',        level: 0, coords: { x: 20, y: 98 }, accessible: true,  indoor: false },
  ],
  edges: [
    { from: 'mia_grdn',  to: 'gate_1',     distance: 100, travel: 'walk',      stepFree: true,  capacity: 2000, bidirectional: false },
    { from: 'gate_1',    to: 'conc_south', distance:  80, travel: 'walk',      stepFree: true,  capacity:  850, bidirectional: true  },
    { from: 'gate_2',    to: 'conc_north', distance:  80, travel: 'walk',      stepFree: true,  capacity:  750, bidirectional: true  },
    { from: 'gate_3',    to: 'conc_east',  distance:  85, travel: 'walk',      stepFree: true,  capacity:  800, bidirectional: true  },
    { from: 'gate_4',    to: 'conc_west',  distance:  85, travel: 'walk',      stepFree: true,  capacity:  800, bidirectional: true  },
    { from: 'conc_south',to: 'conc_east',  distance: 145, travel: 'walk',      stepFree: true,  capacity:  600, bidirectional: true  },
    { from: 'conc_east', to: 'conc_north', distance: 145, travel: 'walk',      stepFree: true,  capacity:  600, bidirectional: true  },
    { from: 'conc_north',to: 'conc_west',  distance: 145, travel: 'walk',      stepFree: true,  capacity:  600, bidirectional: true  },
    { from: 'conc_west', to: 'conc_south', distance: 145, travel: 'walk',      stepFree: true,  capacity:  600, bidirectional: true  },
    { from: 'conc_south',to: 'shade_deck', distance:  40, travel: 'walk',      stepFree: true,  capacity:  500, bidirectional: true  },
    { from: 'conc_east', to: 'upper_e',    distance:  28, travel: 'ramp',      stepFree: true,  capacity:  250, bidirectional: true  },
    { from: 'conc_west', to: 'upper_w',    distance:  28, travel: 'ramp',      stepFree: true,  capacity:  250, bidirectional: true  },
    { from: 'conc_east', to: 'upper_e',    distance:  28, travel: 'elevator',  stepFree: true,  capacity:   12, bidirectional: true  },
    { from: 'upper_e',   to: 'upper_w',    distance: 185, travel: 'walk',      stepFree: true,  capacity:  380, bidirectional: true  },
    { from: 'conc_south',to: 'field_s',    distance:  55, travel: 'walk',      stepFree: true,  capacity:  280, bidirectional: true  },
    { from: 'conc_east', to: 'club_1',     distance:  48, travel: 'walk',      stepFree: true,  capacity:  200, bidirectional: true  },
    { from: 'parking_hub',to:'gate_4',     distance: 220, travel: 'walk',      stepFree: true,  capacity: 1500, bidirectional: false },
  ],
  facilities: [
    { id: 'hr_trn_1', type: 'turnstile',          nodeId: 'gate_1',     name: 'Gate 1 Turnstiles',      description: '22 lanes, mobile ticket scan',                accessible: true,  capacity: 1100 },
    { id: 'hr_trn_2', type: 'turnstile',          nodeId: 'gate_2',     name: 'Gate 2 Turnstiles',      description: '16 lanes',                                    accessible: true,  capacity:  800 },
    { id: 'hr_trn_3', type: 'turnstile',          nodeId: 'gate_3',     name: 'Gate 3 Turnstiles',      description: '18 lanes',                                    accessible: true,  capacity:  900 },
    { id: 'hr_trn_4', type: 'turnstile',          nodeId: 'gate_4',     name: 'Gate 4 Turnstiles',      description: '18 lanes',                                    accessible: true,  capacity:  900 },
    { id: 'hr_rst_s', type: 'restroom',           nodeId: 'conc_south', name: 'Restrooms – South',      description: '12 stalls per side',                          accessible: false, capacity: 120  },
    { id: 'hr_rst_n', type: 'restroom',           nodeId: 'conc_north', name: 'Restrooms – North',      description: '10 stalls per side',                          accessible: false, capacity: 100  },
    { id: 'hr_arc',   type: 'accessible_restroom', nodeId: 'conc_west', name: 'ADA Restroom – West',    description: 'Accessible, changing table',                  accessible: true,  capacity:   4  },
    { id: 'hr_fca',   type: 'food_court',         nodeId: 'shade_deck', name: 'Shade Deck Food Zone',   description: 'Latin & Caribbean cuisine, 25 vendors',       accessible: true,  capacity: 600  },
    { id: 'hr_fcb',   type: 'food_court',         nodeId: 'conc_east',  name: 'East Concessions',       description: 'Classic stadium fare & craft beer',           accessible: true,  capacity: 320  },
    { id: 'hr_fa1',   type: 'first_aid',          nodeId: 'conc_east',  name: 'First Aid – East',       description: 'EMT unit, heat emergency protocol',           accessible: true,  capacity:  12  },
    { id: 'hr_fa2',   type: 'first_aid',          nodeId: 'field_s',    name: 'First Aid – Field',      description: 'Full trauma response, physician on duty',     accessible: true,  capacity:  20  },
    { id: 'hr_atm',   type: 'atm',                nodeId: 'conc_south', name: 'ATM Bank',               description: '8 machines',                                  accessible: true                 },
    { id: 'hr_wat',   type: 'water_station',      nodeId: 'conc_south', name: 'Hydration Station',      description: 'Cool chilled water, misting station nearby',  accessible: true                 },
    { id: 'hr_chg',   type: 'charging_station',   nodeId: 'club_1',     name: 'Charging Lounge',        description: '50 USB pads',                                 accessible: true                 },
    { id: 'hr_merch', type: 'merchandise',        nodeId: 'mia_grdn',   name: 'Fan Zone FIFA Store',    description: 'Outdoor WC 2026 merchandise village',         accessible: true,  capacity: 400  },
    { id: 'hr_sens',  type: 'sensory_room',       nodeId: 'conc_west',  name: 'Sensory Quiet Room',     description: 'Autism-friendly, air-conditioned',            accessible: true,  capacity:  15  },
    { id: 'hr_vip',   type: 'vip_lounge',         nodeId: 'club_1',     name: 'Hard Rock Social Club',  description: 'Premium hospitality, live DJ lounge',         accessible: true,  capacity: 600  },
    { id: 'hr_park',  type: 'parking',            nodeId: 'parking_hub',name: 'Smart Parking Hub',      description: 'EV charging, real-time availability',         accessible: true                 },
    { id: 'hr_fam',   type: 'family_room',        nodeId: 'conc_north', name: 'Family Lounge North',    description: 'Nursing & family rest area',                  accessible: true,  capacity:  20  },
    { id: 'hr_prs',   type: 'press_area',         nodeId: 'conc_north', name: 'Media Centre',           description: 'FIFA press credentials required',             accessible: true,  capacity: 200  },
  ],
};

const mercedesbenz: VenueGraph = {
  venueId: 'mercedesbenz',
  venueName: 'Mercedes-Benz Stadium',
  city: 'Atlanta, GA',
  country: 'USA',
  capacity: 71000,
  nodes: [
    { id: 'gate_1',     name: 'Gate 1 – NE Entry',              section: 'NE Exterior',     level: 0, coords: { x: 72, y:  8 }, accessible: true,  indoor: false },
    { id: 'gate_2',     name: 'Gate 2 – SE Entry',              section: 'SE Exterior',     level: 0, coords: { x: 92, y: 52 }, accessible: true,  indoor: false },
    { id: 'gate_3',     name: 'Gate 3 – South Entry',           section: 'South Exterior',  level: 0, coords: { x: 50, y: 93 }, accessible: true,  indoor: false },
    { id: 'gate_4',     name: 'Gate 4 – SW Entry',              section: 'SW Exterior',     level: 0, coords: { x:  8, y: 72 }, accessible: true,  indoor: false },
    { id: 'gate_5',     name: 'Gate 5 – West Entry',            section: 'West Exterior',   level: 0, coords: { x:  8, y: 30 }, accessible: true,  indoor: false },
    { id: 'halo_ring',  name: 'Halo Board Concourse',           section: 'Main Concourse',  level: 1, coords: { x: 50, y: 50 }, accessible: true,  indoor: true  },
    { id: 'conc_ne',    name: 'Concourse NE',                   section: 'Main Concourse',  level: 1, coords: { x: 68, y: 25 }, accessible: true,  indoor: true  },
    { id: 'conc_se',    name: 'Concourse SE',                   section: 'Main Concourse',  level: 1, coords: { x: 75, y: 62 }, accessible: true,  indoor: true  },
    { id: 'conc_sw',    name: 'Concourse SW',                   section: 'Main Concourse',  level: 1, coords: { x: 25, y: 75 }, accessible: true,  indoor: true  },
    { id: 'conc_nw',    name: 'Concourse NW',                   section: 'Main Concourse',  level: 1, coords: { x: 22, y: 38 }, accessible: true,  indoor: true  },
    { id: 'upper_ne',   name: 'Upper Tier NE',                  section: 'Upper Bowl',      level: 2, coords: { x: 75, y: 20 }, accessible: true,  indoor: true  },
    { id: 'upper_sw',   name: 'Upper Tier SW',                  section: 'Upper Bowl',      level: 2, coords: { x: 22, y: 78 }, accessible: true,  indoor: true  },
    { id: 'field_e',    name: 'Field Access East',              section: 'Field Level',     level: 0, coords: { x: 60, y: 50 }, accessible: true,  indoor: true  },
    { id: 'star_lounge',name: 'Star Lounge Club',               section: 'Club Level',      level: 1, coords: { x: 55, y: 35 }, accessible: true,  indoor: true  },
    { id: 'marta_hub',  name: 'MARTA Rail Hub',                 section: 'Exterior',        level: 0, coords: { x: 50, y: 98 }, accessible: true,  indoor: false },
  ],
  edges: [
    { from: 'marta_hub',  to: 'gate_3',    distance: 110, travel: 'walk',      stepFree: true,  capacity: 3000, bidirectional: false },
    { from: 'gate_1',     to: 'conc_ne',   distance:  75, travel: 'walk',      stepFree: true,  capacity:  750, bidirectional: true  },
    { from: 'gate_2',     to: 'conc_se',   distance:  80, travel: 'walk',      stepFree: true,  capacity:  800, bidirectional: true  },
    { from: 'gate_3',     to: 'conc_sw',   distance:  80, travel: 'walk',      stepFree: true,  capacity:  800, bidirectional: true  },
    { from: 'gate_4',     to: 'conc_sw',   distance:  70, travel: 'walk',      stepFree: true,  capacity:  700, bidirectional: true  },
    { from: 'gate_5',     to: 'conc_nw',   distance:  70, travel: 'walk',      stepFree: true,  capacity:  700, bidirectional: true  },
    { from: 'conc_ne',    to: 'conc_se',   distance: 140, travel: 'walk',      stepFree: true,  capacity:  600, bidirectional: true  },
    { from: 'conc_se',    to: 'conc_sw',   distance: 140, travel: 'walk',      stepFree: true,  capacity:  600, bidirectional: true  },
    { from: 'conc_sw',    to: 'conc_nw',   distance: 140, travel: 'walk',      stepFree: true,  capacity:  600, bidirectional: true  },
    { from: 'conc_nw',    to: 'conc_ne',   distance: 140, travel: 'walk',      stepFree: true,  capacity:  600, bidirectional: true  },
    { from: 'conc_ne',    to: 'halo_ring', distance:  50, travel: 'walk',      stepFree: true,  capacity:  500, bidirectional: true  },
    { from: 'conc_ne',    to: 'upper_ne',  distance:  28, travel: 'escalator', stepFree: false, capacity:  200, bidirectional: false },
    { from: 'conc_ne',    to: 'upper_ne',  distance:  28, travel: 'elevator',  stepFree: true,  capacity:   15, bidirectional: true  },
    { from: 'conc_sw',    to: 'upper_sw',  distance:  28, travel: 'escalator', stepFree: false, capacity:  200, bidirectional: false },
    { from: 'conc_sw',    to: 'upper_sw',  distance:  28, travel: 'elevator',  stepFree: true,  capacity:   15, bidirectional: true  },
    { from: 'halo_ring',  to: 'field_e',   distance:  55, travel: 'ramp',      stepFree: true,  capacity:  300, bidirectional: true  },
    { from: 'halo_ring',  to: 'star_lounge',distance: 35, travel: 'walk',      stepFree: true,  capacity:  200, bidirectional: true  },
  ],
  facilities: [
    { id: 'mb_trn_1', type: 'turnstile',          nodeId: 'gate_1',     name: 'Gate 1 Turnstiles',      description: '16 lanes',                                    accessible: true,  capacity:  800 },
    { id: 'mb_trn_2', type: 'turnstile',          nodeId: 'gate_2',     name: 'Gate 2 Turnstiles',      description: '18 lanes',                                    accessible: true,  capacity:  900 },
    { id: 'mb_trn_3', type: 'turnstile',          nodeId: 'gate_3',     name: 'Gate 3 Turnstiles',      description: '22 lanes, main gate',                         accessible: true,  capacity: 1100 },
    { id: 'mb_trn_4', type: 'turnstile',          nodeId: 'gate_4',     name: 'Gate 4 Turnstiles',      description: '16 lanes',                                    accessible: true,  capacity:  800 },
    { id: 'mb_trn_5', type: 'turnstile',          nodeId: 'gate_5',     name: 'Gate 5 Turnstiles',      description: '14 lanes',                                    accessible: true,  capacity:  700 },
    { id: 'mb_rst_ne',type: 'restroom',           nodeId: 'conc_ne',    name: 'Restrooms – NE',         description: '14 stalls per side',                          accessible: false, capacity: 140  },
    { id: 'mb_rst_sw',type: 'restroom',           nodeId: 'conc_sw',    name: 'Restrooms – SW',         description: '12 stalls per side',                          accessible: false, capacity: 120  },
    { id: 'mb_arc',   type: 'accessible_restroom', nodeId: 'conc_nw',   name: 'ADA Restroom – NW',      description: 'Accessible, companion care available',        accessible: true,  capacity:   4  },
    { id: 'mb_fca',   type: 'food_court',         nodeId: 'halo_ring',  name: 'Halo Ring Food Hall',    description: '$5 food menu, 40 vendors, Atlanta culture',   accessible: true,  capacity: 800  },
    { id: 'mb_fcb',   type: 'food_court',         nodeId: 'conc_se',    name: 'SE Concessions',         description: 'Southern BBQ & local favourites',             accessible: true,  capacity: 350  },
    { id: 'mb_fa1',   type: 'first_aid',          nodeId: 'conc_ne',    name: 'First Aid – NE',         description: 'EMT staffed, AED available',                  accessible: true,  capacity:  12  },
    { id: 'mb_fa2',   type: 'first_aid',          nodeId: 'field_e',    name: 'First Aid – Field',      description: 'Trauma response & physician',                 accessible: true,  capacity:  20  },
    { id: 'mb_atm',   type: 'atm',                nodeId: 'halo_ring',  name: 'ATM Centre – Halo',      description: '10 machines, contactless cash',               accessible: true                 },
    { id: 'mb_wat',   type: 'water_station',      nodeId: 'conc_sw',    name: 'Water Station SW',       description: 'Free refill, filtered & chilled',             accessible: true                 },
    { id: 'mb_chg',   type: 'charging_station',   nodeId: 'star_lounge',name: 'Charging Lounge',        description: '80 USB & wireless pads',                      accessible: true                 },
    { id: 'mb_merch', type: 'merchandise',        nodeId: 'conc_ne',    name: 'FIFA WC Store – MBS',    description: 'Official WC 2026 merchandise',                accessible: true,  capacity: 300  },
    { id: 'mb_sens',  type: 'sensory_room',       nodeId: 'conc_nw',    name: 'Sensory Inclusion Room', description: 'KultureCity certified quiet space',           accessible: true,  capacity:  18  },
    { id: 'mb_vip',   type: 'vip_lounge',         nodeId: 'star_lounge',name: 'Star Lounge',            description: 'All-inclusive premium hospitality',           accessible: true,  capacity: 450  },
    { id: 'mb_mta',   type: 'transit_hub',        nodeId: 'marta_hub',  name: 'MARTA Rail Hub',         description: 'Vine City & GWCC/CNN Center stations',       accessible: true                 },
    { id: 'mb_prs',   type: 'press_area',         nodeId: 'conc_ne',    name: 'FIFA Media Centre',      description: 'Press tribune, broadcast compound',           accessible: true,  capacity: 280  },
  ],
};

const lincolnfinancial: VenueGraph = {
  venueId: 'lincolnfinancial',
  venueName: 'Lincoln Financial Field',
  city: 'Philadelphia, PA',
  country: 'USA',
  capacity: 69796,
  nodes: [
    { id: 'gate_a',     name: 'Gate A – Northeast Entry',      section: 'NE Exterior',     level: 0, coords: { x: 78, y: 10 }, accessible: true,  indoor: false },
    { id: 'gate_b',     name: 'Gate B – South Entry',          section: 'South Exterior',  level: 0, coords: { x: 50, y: 93 }, accessible: true,  indoor: false },
    { id: 'gate_c',     name: 'Gate C – West Entry',           section: 'West Exterior',   level: 0, coords: { x:  8, y: 50 }, accessible: true,  indoor: false },
    { id: 'gate_d',     name: 'Gate D – East Entry',           section: 'East Exterior',   level: 0, coords: { x: 92, y: 50 }, accessible: true,  indoor: false },
    { id: 'conc_south', name: 'Main Concourse South',          section: 'Main Concourse',  level: 1, coords: { x: 50, y: 77 }, accessible: true,  indoor: false },
    { id: 'conc_north', name: 'Main Concourse North',          section: 'Main Concourse',  level: 1, coords: { x: 50, y: 23 }, accessible: true,  indoor: false },
    { id: 'conc_east',  name: 'Main Concourse East',           section: 'Main Concourse',  level: 1, coords: { x: 76, y: 50 }, accessible: true,  indoor: false },
    { id: 'conc_west',  name: 'Main Concourse West',           section: 'Main Concourse',  level: 1, coords: { x: 24, y: 50 }, accessible: true,  indoor: false },
    { id: 'upper_e',    name: 'Upper Level East',              section: 'Upper Bowl',      level: 2, coords: { x: 82, y: 50 }, accessible: true,  indoor: false },
    { id: 'upper_w',    name: 'Upper Level West',              section: 'Upper Bowl',      level: 2, coords: { x: 18, y: 50 }, accessible: true,  indoor: false },
    { id: 'field_s',    name: 'Field Access South',            section: 'Field Level',     level: 0, coords: { x: 50, y: 62 }, accessible: true,  indoor: false },
    { id: 'club_e',     name: 'Lincoln Club East',             section: 'Club Level',      level: 1, coords: { x: 70, y: 38 }, accessible: true,  indoor: true  },
    { id: 'tailgate',   name: 'Tailgate & Fan Zone',           section: 'South Exterior',  level: 0, coords: { x: 50, y: 98 }, accessible: true,  indoor: false },
    { id: 'septa_hub',  name: 'SEPTA Broad St Hub',           section: 'Exterior',        level: 0, coords: { x: 15, y: 95 }, accessible: true,  indoor: false },
    { id: 'sensory_sw', name: 'Sensory Room SW',               section: 'Main Concourse',  level: 1, coords: { x: 22, y: 68 }, accessible: true,  indoor: true  },
  ],
  edges: [
    { from: 'septa_hub',  to: 'gate_c',     distance: 250, travel: 'walk',      stepFree: true,  capacity: 2500, bidirectional: false },
    { from: 'tailgate',   to: 'gate_b',     distance:  90, travel: 'walk',      stepFree: true,  capacity: 2000, bidirectional: false },
    { from: 'gate_a',     to: 'conc_north', distance:  80, travel: 'walk',      stepFree: true,  capacity:  750, bidirectional: true  },
    { from: 'gate_b',     to: 'conc_south', distance:  75, travel: 'walk',      stepFree: true,  capacity:  900, bidirectional: true  },
    { from: 'gate_c',     to: 'conc_west',  distance:  80, travel: 'walk',      stepFree: true,  capacity:  800, bidirectional: true  },
    { from: 'gate_d',     to: 'conc_east',  distance:  80, travel: 'walk',      stepFree: true,  capacity:  800, bidirectional: true  },
    { from: 'conc_south', to: 'conc_east',  distance: 145, travel: 'walk',      stepFree: true,  capacity:  600, bidirectional: true  },
    { from: 'conc_east',  to: 'conc_north', distance: 145, travel: 'walk',      stepFree: true,  capacity:  600, bidirectional: true  },
    { from: 'conc_north', to: 'conc_west',  distance: 145, travel: 'walk',      stepFree: true,  capacity:  600, bidirectional: true  },
    { from: 'conc_west',  to: 'conc_south', distance: 145, travel: 'walk',      stepFree: true,  capacity:  600, bidirectional: true  },
    { from: 'conc_east',  to: 'upper_e',    distance:  27, travel: 'escalator', stepFree: false, capacity:  200, bidirectional: false },
    { from: 'conc_east',  to: 'upper_e',    distance:  27, travel: 'elevator',  stepFree: true,  capacity:   12, bidirectional: true  },
    { from: 'conc_west',  to: 'upper_w',    distance:  27, travel: 'escalator', stepFree: false, capacity:  200, bidirectional: false },
    { from: 'conc_west',  to: 'upper_w',    distance:  27, travel: 'elevator',  stepFree: true,  capacity:   12, bidirectional: true  },
    { from: 'upper_e',    to: 'upper_w',    distance: 185, travel: 'walk',      stepFree: true,  capacity:  380, bidirectional: true  },
    { from: 'conc_south', to: 'field_s',    distance:  52, travel: 'ramp',      stepFree: true,  capacity:  280, bidirectional: true  },
    { from: 'conc_east',  to: 'club_e',     distance:  48, travel: 'walk',      stepFree: true,  capacity:  200, bidirectional: true  },
    { from: 'conc_west',  to: 'sensory_sw', distance:  40, travel: 'walk',      stepFree: true,  capacity:  150, bidirectional: true  },
  ],
  facilities: [
    { id: 'lf_trn_a', type: 'turnstile',          nodeId: 'gate_a',     name: 'Gate A Turnstiles',      description: '16 lanes',                                    accessible: true,  capacity:  800 },
    { id: 'lf_trn_b', type: 'turnstile',          nodeId: 'gate_b',     name: 'Gate B Turnstiles',      description: '22 lanes, main entry',                        accessible: true,  capacity: 1100 },
    { id: 'lf_trn_c', type: 'turnstile',          nodeId: 'gate_c',     name: 'Gate C Turnstiles',      description: '18 lanes',                                    accessible: true,  capacity:  900 },
    { id: 'lf_trn_d', type: 'turnstile',          nodeId: 'gate_d',     name: 'Gate D Turnstiles',      description: '18 lanes',                                    accessible: true,  capacity:  900 },
    { id: 'lf_rst_s', type: 'restroom',           nodeId: 'conc_south', name: 'Restrooms – South',      description: '14 stalls per side',                          accessible: false, capacity: 140  },
    { id: 'lf_rst_n', type: 'restroom',           nodeId: 'conc_north', name: 'Restrooms – North',      description: '10 stalls per side',                          accessible: false, capacity: 100  },
    { id: 'lf_arc',   type: 'accessible_restroom', nodeId: 'sensory_sw', name: 'ADA Restroom – SW',     description: 'Fully accessible, companion care',            accessible: true,  capacity:   4  },
    { id: 'lf_fca',   type: 'food_court',         nodeId: 'tailgate',   name: 'Philly Fan Zone Eats',   description: 'Cheesesteaks & local Philly fare, outdoor',   accessible: true,  capacity: 600  },
    { id: 'lf_fcb',   type: 'food_court',         nodeId: 'conc_east',  name: 'East Concessions',       description: 'Quick-serve, mobile ordering',                accessible: true,  capacity: 320  },
    { id: 'lf_fa1',   type: 'first_aid',          nodeId: 'conc_south', name: 'First Aid – South',      description: 'EMT staffed, AED on site',                    accessible: true,  capacity:  12  },
    { id: 'lf_fa2',   type: 'first_aid',          nodeId: 'field_s',    name: 'First Aid – Field',      description: 'Trauma bay, physician',                       accessible: true,  capacity:  20  },
    { id: 'lf_atm',   type: 'atm',                nodeId: 'conc_east',  name: 'ATM Bank – East',        description: '8 machines',                                  accessible: true                 },
    { id: 'lf_wat',   type: 'water_station',      nodeId: 'conc_west',  name: 'Water Station West',     description: 'Free refill station, 8 taps',                 accessible: true                 },
    { id: 'lf_chg',   type: 'charging_station',   nodeId: 'club_e',     name: 'Charging Hub – Club',    description: '40 USB & wireless pads',                      accessible: true                 },
    { id: 'lf_merch', type: 'merchandise',        nodeId: 'conc_south', name: 'FIFA WC Official Store', description: 'WC 2026 branded merchandise',                 accessible: true,  capacity: 250  },
    { id: 'lf_sens',  type: 'sensory_room',       nodeId: 'sensory_sw', name: 'Sensory Quiet Room',     description: 'Low-stimulation, noise-cancelling headsets',  accessible: true,  capacity:  15  },
    { id: 'lf_vip',   type: 'vip_lounge',         nodeId: 'club_e',     name: 'Lincoln Club',           description: 'Premium club level hospitality',              accessible: true,  capacity: 400  },
    { id: 'lf_trn',   type: 'transit_hub',        nodeId: 'septa_hub',  name: 'SEPTA – Pattison Ave',   description: 'Broad Street Line direct to Center City',     accessible: true                 },
    { id: 'lf_prs',   type: 'press_area',         nodeId: 'conc_north', name: 'FIFA Media Centre',      description: 'Press tribune & broadcast area',              accessible: true,  capacity: 220  },
  ],
};

const gillette: VenueGraph = {
  venueId: 'gillette',
  venueName: 'Gillette Stadium',
  city: 'Foxborough, MA',
  country: 'USA',
  capacity: 65878,
  nodes: [
    { id: 'gate_a',       name: 'Gate A – South Main Entry',   section: 'South Exterior',   level: 0, coords: { x: 50, y: 93 }, accessible: true,  indoor: false },
    { id: 'gate_b',       name: 'Gate B – North Entry',        section: 'North Exterior',   level: 0, coords: { x: 50, y:  7 }, accessible: true,  indoor: false },
    { id: 'gate_c',       name: 'Gate C – East Entry',         section: 'East Exterior',    level: 0, coords: { x: 92, y: 50 }, accessible: true,  indoor: false },
    { id: 'gate_d',       name: 'Gate D – West Entry',         section: 'West Exterior',    level: 0, coords: { x:  8, y: 50 }, accessible: true,  indoor: false },
    { id: 'patriot_place',name: 'Patriot Place Mall Entry',    section: 'Patriot Place',    level: 0, coords: { x: 15, y: 92 }, accessible: true,  indoor: false },
    { id: 'conc_south',   name: 'Lower Concourse South',       section: 'Main Concourse',   level: 1, coords: { x: 50, y: 76 }, accessible: true,  indoor: false },
    { id: 'conc_north',   name: 'Lower Concourse North',       section: 'Main Concourse',   level: 1, coords: { x: 50, y: 24 }, accessible: true,  indoor: false },
    { id: 'conc_east',    name: 'Lower Concourse East',        section: 'Main Concourse',   level: 1, coords: { x: 76, y: 50 }, accessible: true,  indoor: false },
    { id: 'conc_west',    name: 'Lower Concourse West',        section: 'Main Concourse',   level: 1, coords: { x: 24, y: 50 }, accessible: true,  indoor: false },
    { id: 'upper_e',      name: 'Upper Level East',            section: 'Upper Bowl',       level: 2, coords: { x: 82, y: 50 }, accessible: true,  indoor: false },
    { id: 'upper_w',      name: 'Upper Level West',            section: 'Upper Bowl',       level: 2, coords: { x: 18, y: 50 }, accessible: true,  indoor: false },
    { id: 'field_n',      name: 'Field Access North',          section: 'Field Level',      level: 0, coords: { x: 50, y: 42 }, accessible: true,  indoor: false },
    { id: 'lighthouse',   name: 'Lighthouse Club',             section: 'Club Level',       level: 1, coords: { x: 65, y: 35 }, accessible: true,  indoor: true  },
    { id: 'commuter_hub', name: 'Commuter Rail Hub',           section: 'Exterior',         level: 0, coords: { x: 50, y: 98 }, accessible: true,  indoor: false },
    { id: 'tower_bridge', name: 'Stadium Tower Bridge Walk',   section: 'North Exterior',   level: 1, coords: { x: 50, y: 12 }, accessible: false, indoor: false },
  ],
  edges: [
    { from: 'commuter_hub',  to: 'gate_a',      distance: 130, travel: 'walk',      stepFree: true,  capacity: 2500, bidirectional: false },
    { from: 'patriot_place', to: 'gate_d',      distance: 140, travel: 'walk',      stepFree: true,  capacity: 1500, bidirectional: false },
    { from: 'gate_a',        to: 'conc_south',  distance:  78, travel: 'walk',      stepFree: true,  capacity:  850, bidirectional: true  },
    { from: 'gate_b',        to: 'conc_north',  distance:  75, travel: 'walk',      stepFree: true,  capacity:  750, bidirectional: true  },
    { from: 'gate_c',        to: 'conc_east',   distance:  80, travel: 'walk',      stepFree: true,  capacity:  800, bidirectional: true  },
    { from: 'gate_d',        to: 'conc_west',   distance:  80, travel: 'walk',      stepFree: true,  capacity:  800, bidirectional: true  },
    { from: 'conc_south',    to: 'conc_east',   distance: 140, travel: 'walk',      stepFree: true,  capacity:  580, bidirectional: true  },
    { from: 'conc_east',     to: 'conc_north',  distance: 140, travel: 'walk',      stepFree: true,  capacity:  580, bidirectional: true  },
    { from: 'conc_north',    to: 'conc_west',   distance: 140, travel: 'walk',      stepFree: true,  capacity:  580, bidirectional: true  },
    { from: 'conc_west',     to: 'conc_south',  distance: 140, travel: 'walk',      stepFree: true,  capacity:  580, bidirectional: true  },
    { from: 'conc_east',     to: 'upper_e',     distance:  26, travel: 'escalator', stepFree: false, capacity:  190, bidirectional: false },
    { from: 'conc_east',     to: 'upper_e',     distance:  26, travel: 'elevator',  stepFree: true,  capacity:   12, bidirectional: true  },
    { from: 'conc_west',     to: 'upper_w',     distance:  26, travel: 'escalator', stepFree: false, capacity:  190, bidirectional: false },
    { from: 'conc_west',     to: 'upper_w',     distance:  26, travel: 'elevator',  stepFree: true,  capacity:   12, bidirectional: true  },
    { from: 'upper_e',       to: 'upper_w',     distance: 175, travel: 'walk',      stepFree: true,  capacity:  350, bidirectional: true  },
    { from: 'conc_north',    to: 'field_n',     distance:  50, travel: 'ramp',      stepFree: true,  capacity:  260, bidirectional: true  },
    { from: 'conc_east',     to: 'lighthouse',  distance:  45, travel: 'walk',      stepFree: true,  capacity:  180, bidirectional: true  },
    { from: 'gate_b',        to: 'tower_bridge',distance:  40, travel: 'stairs',    stepFree: false, capacity:  300, bidirectional: true  },
  ],
  facilities: [
    { id: 'gi_trn_a', type: 'turnstile',          nodeId: 'gate_a',      name: 'Gate A Turnstiles',      description: '20 lanes, main gate',                         accessible: true,  capacity: 1000 },
    { id: 'gi_trn_b', type: 'turnstile',          nodeId: 'gate_b',      name: 'Gate B Turnstiles',      description: '14 lanes',                                    accessible: true,  capacity:  700 },
    { id: 'gi_trn_c', type: 'turnstile',          nodeId: 'gate_c',      name: 'Gate C Turnstiles',      description: '16 lanes',                                    accessible: true,  capacity:  800 },
    { id: 'gi_trn_d', type: 'turnstile',          nodeId: 'gate_d',      name: 'Gate D Turnstiles',      description: '16 lanes',                                    accessible: true,  capacity:  800 },
    { id: 'gi_rst_s', type: 'restroom',           nodeId: 'conc_south',  name: 'Restrooms – South',      description: '12 stalls per side',                          accessible: false, capacity: 120  },
    { id: 'gi_rst_e', type: 'restroom',           nodeId: 'conc_east',   name: 'Restrooms – East',       description: '10 stalls per side',                          accessible: false, capacity: 100  },
    { id: 'gi_arc',   type: 'accessible_restroom', nodeId: 'conc_west',  name: 'ADA Restroom – West',    description: 'Fully accessible, companion care',            accessible: true,  capacity:   4  },
    { id: 'gi_fca',   type: 'food_court',         nodeId: 'patriot_place', name: 'Patriot Place Food',   description: 'Full restaurant row, 18 outlets',            accessible: true,  capacity: 500  },
    { id: 'gi_fcb',   type: 'food_court',         nodeId: 'conc_south',  name: 'South Concessions',      description: 'Classic fare & New England clam chowder',     accessible: true,  capacity: 300  },
    { id: 'gi_fa1',   type: 'first_aid',          nodeId: 'conc_east',   name: 'First Aid – East',       description: 'EMT staffed, AED & warming station',          accessible: true,  capacity:  12  },
    { id: 'gi_fa2',   type: 'first_aid',          nodeId: 'field_n',     name: 'First Aid – Field',      description: 'Trauma bay, sports medicine',                 accessible: true,  capacity:  20  },
    { id: 'gi_atm',   type: 'atm',                nodeId: 'conc_south',  name: 'ATM Bank – South',       description: '6 machines',                                  accessible: true                 },
    { id: 'gi_wat',   type: 'water_station',      nodeId: 'conc_west',   name: 'Water Station West',     description: '6 chilled taps, reusable cups available',     accessible: true                 },
    { id: 'gi_chg',   type: 'charging_station',   nodeId: 'lighthouse',  name: 'Charging Hub – Lighthouse', description: '40 USB & wireless pads',                  accessible: true                 },
    { id: 'gi_merch', type: 'merchandise',        nodeId: 'conc_south',  name: 'FIFA WC Official Store', description: 'WC 2026 & Patriots merchandise',              accessible: true,  capacity: 200  },
    { id: 'gi_sens',  type: 'sensory_room',       nodeId: 'conc_west',   name: 'Sensory Quiet Room',     description: 'Low-stimulation, weighted blankets',          accessible: true,  capacity:  12  },
    { id: 'gi_vip',   type: 'vip_lounge',         nodeId: 'lighthouse',  name: 'Lighthouse Club',        description: 'Premium club level with harbour views',       accessible: true,  capacity: 350  },
    { id: 'gi_trn',   type: 'transit_hub',        nodeId: 'commuter_hub',name: 'MBTA Commuter Rail',     description: 'Foxboro Station – Providence Line',           accessible: true                 },
    { id: 'gi_fam',   type: 'family_room',        nodeId: 'conc_north',  name: 'Family Lounge North',    description: 'Child-friendly area with nursing room',       accessible: true,  capacity:  20  },
    { id: 'gi_prs',   type: 'press_area',         nodeId: 'conc_north',  name: 'Media Centre',           description: 'Press tribune, photographer pit access',      accessible: true,  capacity: 200  },
  ],
};

export const VENUES: Record<VenueId, VenueGraph> = {
  metlife:          metlife,
  sofi:             sofi,
  attdallas:        attdallas,
  levis:            levis,
  hardrock:         hardrock,
  mercedesbenz:     mercedesbenz,
  lincolnfinancial: lincolnfinancial,
  gillette:         gillette,
};
